### ISSUE TITLE
Make decisions on color, layout etc.

### ISSUE THREAD

**Issue by m-clark** [mclark--/data-manipulation-in-r#2]
Open to suggestions related to theme

**Comment by saberry** [comment]
Seriously?

I think we both know my aesthetic sense is not of the highest caliber, but I will always opt for Alice Blue.

**Comment by saberry** [comment]
As it is, I like how it is simple and clean. In this case, I would turn to the wesanderson stuff. I always like the red from Royal1 as emphasis, but I also like everything from Darjeeling.

**Comment by m-clark** [comment]
Whither papaya whip?

**Comment by m-clark** [comment]
What about [this](http://apps2.eere.energy.gov/wind/windexchange/pdfs/wind_maps/us_windmap_80meters.pdf) for a color scheme guideline?  I've never thought of using a diverging-sequential palette with a couple random colors thrown in.

**Comment by saberry** [comment]
I like the idea, but I really cannot get into the colors on that document. Perhaps I will take a look at the colorbrewer website.

**Comment by saberry** [comment]
Here are some that appeal to my eye:

Sequential PuBu, GnBu, and PuBuGn and diverging RdBu.

**Comment by m-clark** [comment]
I was kidding mind you. That graph's color scheme makes no damn sense.

**Comment by m-clark** [comment]
emph: red royal1
package: R/dodger blue
function: #ff5500?

**Comment by saberry** [comment]
I think that should work. I will get those changed and pushed up today

**Comment by saberry** [comment]
I see that I am too late.

**Comment by m-clark** [comment]
Still, keep an eye out for any that were missed.  Only reason I haven't closed is that there might be some stragglers that still need highlighting.
