### ISSUE TITLE
lazerhawk etc.?

### ISSUE THREAD

**Issue by m-clark** [mclark--/data-manipulation-in-r#5]
There should be some mention of the likes of Lazerhawk, Timecop1983, and FM-84. They're practically dependencies.

**Comment by saberry** [comment]
Mention? I really thought we were going to have a soundtrack going the whole time. I have the perfect place to sync up the solo in Distress Signal to the slides. It will be like Dark Side of the Rainbow, but cooler.

**Comment by m-clark** [comment]
Excellent
